---
title: "Mrode Ch1"
author: "Zhikai Yang"
date: 10-17-2018
output:
  html_document: default
  html_notebook: default
  pdf_document: default
  word_document: default
---

## Section 1:

Basic model
$$y_{ij} = \mu_i + g_i + e_{ij} \hspace{150pt} (1.1)$$

### q1. Is the definition of $e_{ij}$ correct? (p1)

> Yang: must be correct. $j$ here indicate the traits.


Ignoring dominance and epistasis, the model becomes$$y_{ij} = \mu_i + g_{ai} + e_{ij}^* \hspace{150pt} (1.2)$$

### q2. It is assumed that var(y), var(g)and var($e^*$) are known, but how are var(g)and var($e^*$) calculated?(p2)

q3. From Eqn 1.2, the problem of predicting breeding value reduces to that of adjusting phenotypic observations for identifiable
non-random environmental effects and appropriately weighting the records of animals and their available relatives. How is this done specifically? (p2)




1.3 Breeding Value Prediction from the Animal’s Own Performance

1.3.1 Estimated breeding value(EBV) from single record:
$$\hat{a_i} = b(y_i - \mu) \hspace{150pt} (1.3)$$
$$b = cov(a, y)/var(y)=cov(a, a+e)/var(y)=\sigma_a^2/\sigma_y^2=h^2$$
q4. How can $\sigma_a^2$(variance of breeding value) be known while we still need to predict a(breedding value)? In this case, $\mu_i$ is a constant, right? if yes, how can you adjust it in q3?(p3)
$$r_{a,y} = cov(a, y)/\sigma_a\sigma_y=\sigma_a^2/\sigma_a\sigma_y=h$$
($r_{a,y}$ : accuracy of prediction, a:true breeding value, y:index to predict the true breeding value)


1.3.2 Estimated breeding value(EBV) from repeated records(p4-5):

q5. With repeated measurements it is assumed that there is additional resemblance between records of an individual due to environmental factors or circumstances that affect the records of the individual permanently.  
                                                  var(y)= var(g) + var(pe) + var(te)  
(var(pe) = variance due to permanent environmental effect; var(te) = variance due to random temporary environmental effect)
                                                  t = (var(g)+var(pe)/var(y))          (1.5)

$$\hat{a_i} = b(\bar{y_i} - \mu) \hspace{150pt} (1.3)$$
$$b = cov(a, \bar{y})/var(\bar{y})=cov(a, g+pe+\sum te/n)/[t+(1-t)/n]\sigma_y^2=nh^2/[1+(n-1)t]$$
$$r_{a,\bar{y}} = cov(a, \bar{y})/\sigma_a\sigma_y=\sigma_a^2/(\sigma_a\sqrt{[t+(1-t)/n]\sigma_y^2})=\sqrt{nh^2/(1+(n-1)t)}=\sqrt{b}$$



1.4 Breeding Value Prediction from Progeny Records(p6-8)

$$\hat{a_i} = b(\bar{y_i} - \mu) \hspace{150pt} (1.8)$$
$$b = cov(a, \bar{y})/var(\bar{y})=cov(a,\frac{1}{2}a_s+\frac{1}{2}a_d+\sum e/n)/[t+(1-t)/n]\sigma^2_y=\frac{1}{2}\sigma^2_a/[\frac{1}{4}h^2+(1-\frac{1}{4}h^2)/n]\sigma^2_y=2n/(n+(4-h^2)/h^2)=2n/(n+k)$$

q6. According to $y= \frac{1}{2}a_s+\frac{1}{2}a_d+e$, if $t=\frac{1}{4}\sigma_a^2/\sigma_y^2=\frac{1}{4}h^2$(is h in terms of $a_s$? is the y in terms of the sire or the daughter? is the h same for grand parents to sire and for sire to daughter?), then $1-t=(\frac{1}{4}\sigma_{a_d}^2+\sigma^2_e)/\sigma_y^2$, why $var(\bar{y})=[t+(1-t)/n]\sigma^2_y$

q7.It is assumed that the progeny are only related through the sire, so why not $\bar{y}=\frac{1}{2}a_s+\frac{1}{2}\sum a_d/n+\sum e/n$


```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
